name: reactWorkflow

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Deploy react app to github pages
      uses: ShawnAlisson/reactjsWorkflow@v1.0.0
